In [2]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.6-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.3-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\andry\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.4-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\andry\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp313-cp313-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.6 MB 5.5 MB/s eta 0:00:02
   ----- ---------------------------------- 1.3/9.6 MB 3.7 MB/s eta 0:00:03
   ---------- ----------------------------- 2.6/9.6 MB 4.7 MB/s eta 0:00:02
   ---------------- ----------------------- 3.9/9.6 MB 5.2 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.6 MB 5.7 MB/s eta 0:00:01
   --------------------------- ------------ 6.6/9.6 MB 5.8 MB/s eta 0:00:01
   --------------------------------- ------ 8.1/9.6 MB 5.8 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.6 MB 6.0 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 5.9 MB/s eta 0:00:00
Downloading numpy-2.5.3-cp313-cp313-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ----- ---------------------------------- 1.6/12.6 MB 6.9 MB/s eta 0:00:02
   ---------- ----------------------------- 3.1/12.6 MB 7.8 MB/s eta 0:00:02
   --------------- ------------------------ 4.7/12.6 MB 7.8 MB/s eta 0:00:02
   -------------------- ------------------- 6.6/12.6 MB 7.8 MB/s eta 0:00:01
   ------------------------- -------------- 7.9/12.6 MB 7.8 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.6 MB 7.3 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.6 MB 7.2 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 6.9 MB/s eta 0:00:00
Downloading tzdata-2026.4-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.5.3 pandas-3.0.6 tzdata-2026.4

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

ruta = r"C:\Users\andry\Downloads\base-saij-normativa-provincial.csv"
df = pd.read_csv(ruta)

df.head()

,provincia_nombre,tipo_norma,numero_norma,estado_vigencia,fecha,fecha_publicacion,nombre_norma,titulo_resumido,titulo_sumario,informacion_digesto,texto_actualizado,provincia_id
0,Buenos Aires,Constitución Provincial,0,"Vigente, de alcance general",1994-09-13,1994-09-14,Constitución de la Provincia de Buenos Aires,CONSTITUCION DE LA PROVINCIA DE BUENOS AIRES,CONSTITUCION PROVINCIAL-DECLARACIONES-DERECHOS...,NaN,www.saij.gob.ar/LPB1000000,6
1,Buenos Aires,Constitución Provincial,0,"Individual, Solo Modificatoria o Sin Eficacia",1934-11-29,1934-11-29,CONSTITUCION DE LA PROVINCIA DE BUENOS AIRES D...,CONSTITUCION DE LA PROVINCIA DE BUENOS AIRES,"DECLARACIONES,DERECHOS Y GARANTIAS-REGIMEN ELE...",NaN,www.saij.gob.ar/LPB0000000,6
2,Buenos Aires,Decreto Ley,10000,"Individual, Solo Modificatoria o Sin Eficacia",1983-07-26,1983-08-26,DLE,NaN,ELECCIONES CONVOCATORIA ELECTORAL,NaN,www.saij.gob.ar/LPB0010000,6
3,Buenos Aires,Decreto Ley,10001,"Vigente, de alcance general",1983-07-26,1983-10-11,DECRETO LEY 10.001,CONVENIO CELEBRADO ENTRE LA PROVINCIA DE BUENO...,CONVENIO DE PARTES-SISTEMA ARGENTINO DE INFORM...,NaN,www.saij.gob.ar/LPB0010001,6
4,Buenos Aires,Decreto Ley,10005,"Individual, Solo Modificatoria o Sin Eficacia",1983-08-15,1983-09-13,DLE 10.005/83,NaN,PRORROGA DE PLAZOS DE PAGO DE IMPUESTO AUTOMOT...,NaN,www.saij.gob.ar/LPB0010005,6

Filtrar los datos solo para las provincias de Tucumán, Formosa y Tierra del Fuego.

In [4]:
provincias = ["Tucumán", "Formosa", "Tierra del Fuego"]

df_filtrado = df[df["provincia_nombre"].isin(provincias)]

df_filtrado

,provincia_nombre,tipo_norma,numero_norma,estado_vigencia,fecha,fecha_publicacion,nombre_norma,titulo_resumido,titulo_sumario,informacion_digesto,texto_actualizado,provincia_id
27815,Formosa,Constitución Provincial,0,"Vigente, de alcance general",2025-09-05,2025-09-08,CONSTITUCION PROVINCIAL,Constitución de la provincia de Formosa,CONSTITUCION PROVINCIAL,NaN,www.saij.gob.ar/LPP2000000,34
27816,Formosa,Constitución Provincial,0,"Individual, Solo Modificatoria o Sin Eficacia",1991-04-03,1991-04-03,CONSTITUCION PROVINCIAL,Constitución de la Provincia de Formosa.,DERECHO CONSTITUCIONAL-CONSTITUCION PROVINCIAL,NaN,www.saij.gob.ar/LPP0000000,34
27817,Formosa,Constitución Provincial,0,"Individual, Solo Modificatoria o Sin Eficacia",2003-07-07,2003-07-08,CONSTITUCION PROVINCIAL,Constitución de la Provincia de Formosa.,DERECHO CONSTITUCIONAL-CONSTITUCION PROVINCIAL,NaN,www.saij.gob.ar/LPP1000000,34
27818,Formosa,Ley,1009,"Vigente, de alcance general",1992-08-06,1992-09-01,LEY 1.009,Código de procedimiento del Tribunal de Familia,DERECHO PROCESAL-COMPETENCIA DE FAMILIA-TRIBUN...,NaN,www.saij.gob.ar/LPP0001009,34
27819,Formosa,Ley,1095,"Vigente, de alcance general",1994-06-02,1994-10-20,LEY 1.095,Establece mecanismos y requisitos para enjuici...,ENJUICIAMIENTO DE MAGISTRADOS-JUICIO POLITICO-...,NaN,www.saij.gob.ar/LPP0001095,34
...,...,...,...,...,...,...,...,...,...,...,...,...
81398,Tucumán,Ley,9987,"Vigente, de alcance general",2026-06-18,2026-07-01,LEY 9.987,Ley Orgánica del Poder Judicial. Colegio de Ju...,Ley Orgánica del Poder Judicial. Colegio de Ju...,NaN,www.saij.gob.ar/LPT0009987,90
81399,Tucumán,Ley,9988,"Vigente, de alcance general",2026-06-18,2026-07-01,LEY 9.988,Código Procesal Administrativo. Modifica la Le...,Código Procesal Administrativo. Modifica la Le...,NaN,www.saij.gob.ar/LPT0009988,90
81400,Tucumán,Ley,9989,"Vigente, de alcance general",2026-06-18,2026-07-06,LEY 9.989,Código Procesal Civil y Comercial de Tucumán. ...,Código Procesal Civil y Comercial de Tucumán. ...,NaN,www.saij.gob.ar/LPT0009989,90
81401,Tucumán,Ley,9990,"Vigente, de alcance general",2026-06-18,2026-07-08,LEY 9.990,Declara de utilidad pública y sujeto a expropi...,Declara de utilidad pública y sujeto a expropi...,NaN,www.saij.gob.ar/LPT0009990,90
81402,Tucumán,Ley,9991,"Vigente, de alcance general",2026-06-18,2026-07-08,LEY 9.991,Sistema de protección del patrimonio cultural ...,Sistema de protección del patrimonio cultural ...,NaN,www.saij.gob.ar/LPT0009991,90

Limpiar columnas vacías o que no aporten información valiosa para su uso.

In [5]:
# Crear una copia para conservar el dataframe original
df_limpio = df_filtrado.copy()

# Eliminar columnas completamente vacías
df_limpio = df_limpio.dropna(axis=1, how="all")

# Eliminar columnas redundantes
df_limpio = df_limpio.drop(columns=["provincia_id"], errors="ignore")

# Mostrar las columnas resultantes
df_limpio.info()

df_limpio.head()

<class 'pandas.DataFrame'>
Index: 2918 entries, 27815 to 81402
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   provincia_nombre   2918 non-null   str
 1   tipo_norma         2918 non-null   str
 2   numero_norma       2918 non-null   int64
 3   estado_vigencia    2918 non-null   str
 4   fecha              2918 non-null   str
 5   fecha_publicacion  2912 non-null   str
 6   nombre_norma       2918 non-null   str
 7   titulo_resumido    2445 non-null   str
 8   titulo_sumario     2915 non-null   str
 9   texto_actualizado  2918 non-null   str
dtypes: int64(1), str(9)
memory usage: 250.8 KB

,provincia_nombre,tipo_norma,numero_norma,estado_vigencia,fecha,fecha_publicacion,nombre_norma,titulo_resumido,titulo_sumario,texto_actualizado
27815,Formosa,Constitución Provincial,0,"Vigente, de alcance general",2025-09-05,2025-09-08,CONSTITUCION PROVINCIAL,Constitución de la provincia de Formosa,CONSTITUCION PROVINCIAL,www.saij.gob.ar/LPP2000000
27816,Formosa,Constitución Provincial,0,"Individual, Solo Modificatoria o Sin Eficacia",1991-04-03,1991-04-03,CONSTITUCION PROVINCIAL,Constitución de la Provincia de Formosa.,DERECHO CONSTITUCIONAL-CONSTITUCION PROVINCIAL,www.saij.gob.ar/LPP0000000
27817,Formosa,Constitución Provincial,0,"Individual, Solo Modificatoria o Sin Eficacia",2003-07-07,2003-07-08,CONSTITUCION PROVINCIAL,Constitución de la Provincia de Formosa.,DERECHO CONSTITUCIONAL-CONSTITUCION PROVINCIAL,www.saij.gob.ar/LPP1000000
27818,Formosa,Ley,1009,"Vigente, de alcance general",1992-08-06,1992-09-01,LEY 1.009,Código de procedimiento del Tribunal de Familia,DERECHO PROCESAL-COMPETENCIA DE FAMILIA-TRIBUN...,www.saij.gob.ar/LPP0001009
27819,Formosa,Ley,1095,"Vigente, de alcance general",1994-06-02,1994-10-20,LEY 1.095,Establece mecanismos y requisitos para enjuici...,ENJUICIAMIENTO DE MAGISTRADOS-JUICIO POLITICO-...,www.saij.gob.ar/LPP0001095

Filtrar datos de normativas de Ley, Decreto Ley y Texto Ordenado Ley.

In [6]:
tipos_normativa = ["Ley", "Decreto Ley", "Texto Ordenado Ley"]

df_normativas = df_limpio[
    df_limpio["tipo_norma"].isin(tipos_normativa)
].copy()

df_normativas

,provincia_nombre,tipo_norma,numero_norma,estado_vigencia,fecha,fecha_publicacion,nombre_norma,titulo_resumido,titulo_sumario,texto_actualizado
27818,Formosa,Ley,1009,"Vigente, de alcance general",1992-08-06,1992-09-01,LEY 1.009,Código de procedimiento del Tribunal de Familia,DERECHO PROCESAL-COMPETENCIA DE FAMILIA-TRIBUN...,www.saij.gob.ar/LPP0001009
27819,Formosa,Ley,1095,"Vigente, de alcance general",1994-06-02,1994-10-20,LEY 1.095,Establece mecanismos y requisitos para enjuici...,ENJUICIAMIENTO DE MAGISTRADOS-JUICIO POLITICO-...,www.saij.gob.ar/LPP0001095
27820,Formosa,Ley,1160,"Vigente, de alcance general",1995-10-26,1995-12-20,LEY 1.160,Ley de protección contra la violencia familiar,DERECHOS HUMANOS-VIOLENCIA FAMILIAR-PROTECCION...,www.saij.gob.ar/LPP0001160
27821,Formosa,Ley,1216,"Vigente, de alcance general",1996-11-07,1996-12-10,LEY 1.216,Carta Orgánica del Tribunal de Cuentas de Form...,TRIBUNAL DE CUENTAS-MIEMBROS DEL TRIBUNAL DE C...,www.saij.gob.ar/LPP0001216
27822,Formosa,Ley,1246,"Vigente, de alcance general",1997-09-04,1997-11-12,LEY 1246,Código de Aguas de Formosa.,CODIGO DE AGUAS-RECURSOS HIDRICOS-CODIGO DE AG...,www.saij.gob.ar/LPP0001246
...,...,...,...,...,...,...,...,...,...,...
81398,Tucumán,Ley,9987,"Vigente, de alcance general",2026-06-18,2026-07-01,LEY 9.987,Ley Orgánica del Poder Judicial. Colegio de Ju...,Ley Orgánica del Poder Judicial. Colegio de Ju...,www.saij.gob.ar/LPT0009987
81399,Tucumán,Ley,9988,"Vigente, de alcance general",2026-06-18,2026-07-01,LEY 9.988,Código Procesal Administrativo. Modifica la Le...,Código Procesal Administrativo. Modifica la Le...,www.saij.gob.ar/LPT0009988
81400,Tucumán,Ley,9989,"Vigente, de alcance general",2026-06-18,2026-07-06,LEY 9.989,Código Procesal Civil y Comercial de Tucumán. ...,Código Procesal Civil y Comercial de Tucumán. ...,www.saij.gob.ar/LPT0009989
81401,Tucumán,Ley,9990,"Vigente, de alcance general",2026-06-18,2026-07-08,LEY 9.990,Declara de utilidad pública y sujeto a expropi...,Declara de utilidad pública y sujeto a expropi...,www.saij.gob.ar/LPT0009990
81402,Tucumán,Ley,9991,"Vigente, de alcance general",2026-06-18,2026-07-08,LEY 9.991,Sistema de protección del patrimonio cultural ...,Sistema de protección del patrimonio cultural ...,www.saij.gob.ar/LPT0009991

Eliminar casos de normativas vetadas.

In [7]:
# Eliminar normativas cuyo estado indique que fueron vetadas
df_sin_vetadas = df_normativas[
    ~df_normativas["estado_vigencia"]
    .fillna("")
    .str.contains("vetad", case=False, na=False)
].copy()

df_sin_vetadas

,provincia_nombre,tipo_norma,numero_norma,estado_vigencia,fecha,fecha_publicacion,nombre_norma,titulo_resumido,titulo_sumario,texto_actualizado
27818,Formosa,Ley,1009,"Vigente, de alcance general",1992-08-06,1992-09-01,LEY 1.009,Código de procedimiento del Tribunal de Familia,DERECHO PROCESAL-COMPETENCIA DE FAMILIA-TRIBUN...,www.saij.gob.ar/LPP0001009
27819,Formosa,Ley,1095,"Vigente, de alcance general",1994-06-02,1994-10-20,LEY 1.095,Establece mecanismos y requisitos para enjuici...,ENJUICIAMIENTO DE MAGISTRADOS-JUICIO POLITICO-...,www.saij.gob.ar/LPP0001095
27820,Formosa,Ley,1160,"Vigente, de alcance general",1995-10-26,1995-12-20,LEY 1.160,Ley de protección contra la violencia familiar,DERECHOS HUMANOS-VIOLENCIA FAMILIAR-PROTECCION...,www.saij.gob.ar/LPP0001160
27821,Formosa,Ley,1216,"Vigente, de alcance general",1996-11-07,1996-12-10,LEY 1.216,Carta Orgánica del Tribunal de Cuentas de Form...,TRIBUNAL DE CUENTAS-MIEMBROS DEL TRIBUNAL DE C...,www.saij.gob.ar/LPP0001216
27822,Formosa,Ley,1246,"Vigente, de alcance general",1997-09-04,1997-11-12,LEY 1246,Código de Aguas de Formosa.,CODIGO DE AGUAS-RECURSOS HIDRICOS-CODIGO DE AG...,www.saij.gob.ar/LPP0001246
...,...,...,...,...,...,...,...,...,...,...
81398,Tucumán,Ley,9987,"Vigente, de alcance general",2026-06-18,2026-07-01,LEY 9.987,Ley Orgánica del Poder Judicial. Colegio de Ju...,Ley Orgánica del Poder Judicial. Colegio de Ju...,www.saij.gob.ar/LPT0009987
81399,Tucumán,Ley,9988,"Vigente, de alcance general",2026-06-18,2026-07-01,LEY 9.988,Código Procesal Administrativo. Modifica la Le...,Código Procesal Administrativo. Modifica la Le...,www.saij.gob.ar/LPT0009988
81400,Tucumán,Ley,9989,"Vigente, de alcance general",2026-06-18,2026-07-06,LEY 9.989,Código Procesal Civil y Comercial de Tucumán. ...,Código Procesal Civil y Comercial de Tucumán. ...,www.saij.gob.ar/LPT0009989
81401,Tucumán,Ley,9990,"Vigente, de alcance general",2026-06-18,2026-07-08,LEY 9.990,Declara de utilidad pública y sujeto a expropi...,Declara de utilidad pública y sujeto a expropi...,www.saij.gob.ar/LPT0009990
81402,Tucumán,Ley,9991,"Vigente, de alcance general",2026-06-18,2026-07-08,LEY 9.991,Sistema de protección del patrimonio cultural ...,Sistema de protección del patrimonio cultural ...,www.saij.gob.ar/LPT0009991

Reemplazar vacíos por “n/d”

In [8]:
df_final = df_sin_vetadas.copy()

# Reemplazar valores nulos y cadenas vacías por "n/d"
df_final = df_final.fillna("n/d")
df_final = df_final.replace(r"^\s*$", "n/d", regex=True)

df_final

,provincia_nombre,tipo_norma,numero_norma,estado_vigencia,fecha,fecha_publicacion,nombre_norma,titulo_resumido,titulo_sumario,texto_actualizado
27818,Formosa,Ley,1009,"Vigente, de alcance general",1992-08-06,1992-09-01,LEY 1.009,Código de procedimiento del Tribunal de Familia,DERECHO PROCESAL-COMPETENCIA DE FAMILIA-TRIBUN...,www.saij.gob.ar/LPP0001009
27819,Formosa,Ley,1095,"Vigente, de alcance general",1994-06-02,1994-10-20,LEY 1.095,Establece mecanismos y requisitos para enjuici...,ENJUICIAMIENTO DE MAGISTRADOS-JUICIO POLITICO-...,www.saij.gob.ar/LPP0001095
27820,Formosa,Ley,1160,"Vigente, de alcance general",1995-10-26,1995-12-20,LEY 1.160,Ley de protección contra la violencia familiar,DERECHOS HUMANOS-VIOLENCIA FAMILIAR-PROTECCION...,www.saij.gob.ar/LPP0001160
27821,Formosa,Ley,1216,"Vigente, de alcance general",1996-11-07,1996-12-10,LEY 1.216,Carta Orgánica del Tribunal de Cuentas de Form...,TRIBUNAL DE CUENTAS-MIEMBROS DEL TRIBUNAL DE C...,www.saij.gob.ar/LPP0001216
27822,Formosa,Ley,1246,"Vigente, de alcance general",1997-09-04,1997-11-12,LEY 1246,Código de Aguas de Formosa.,CODIGO DE AGUAS-RECURSOS HIDRICOS-CODIGO DE AG...,www.saij.gob.ar/LPP0001246
...,...,...,...,...,...,...,...,...,...,...
81398,Tucumán,Ley,9987,"Vigente, de alcance general",2026-06-18,2026-07-01,LEY 9.987,Ley Orgánica del Poder Judicial. Colegio de Ju...,Ley Orgánica del Poder Judicial. Colegio de Ju...,www.saij.gob.ar/LPT0009987
81399,Tucumán,Ley,9988,"Vigente, de alcance general",2026-06-18,2026-07-01,LEY 9.988,Código Procesal Administrativo. Modifica la Le...,Código Procesal Administrativo. Modifica la Le...,www.saij.gob.ar/LPT0009988
81400,Tucumán,Ley,9989,"Vigente, de alcance general",2026-06-18,2026-07-06,LEY 9.989,Código Procesal Civil y Comercial de Tucumán. ...,Código Procesal Civil y Comercial de Tucumán. ...,www.saij.gob.ar/LPT0009989
81401,Tucumán,Ley,9990,"Vigente, de alcance general",2026-06-18,2026-07-08,LEY 9.990,Declara de utilidad pública y sujeto a expropi...,Declara de utilidad pública y sujeto a expropi...,www.saij.gob.ar/LPT0009990
81402,Tucumán,Ley,9991,"Vigente, de alcance general",2026-06-18,2026-07-08,LEY 9.991,Sistema de protección del patrimonio cultural ...,Sistema de protección del patrimonio cultural ...,www.saij.gob.ar/LPT0009991

Guardar en .xlsx y .csv (UTF-8 separador “,”).

In [10]:
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
# Guardar el dataframe final en formato XLSX y CSV
df_final.to_excel("normativas_filtradas.xlsx", index=False)
df_final.to_csv(
    "normativas_filtradas.csv",
    index=False,
    sep=",",
    encoding="utf-8"
)

print("Archivos guardados correctamente.")

Archivos guardados correctamente.

In [12]:
from pathlib import Path

archivos = [
    Path("normativas_filtradas.xlsx"),
    Path("normativas_filtradas.csv")
]

for archivo in archivos:
    print(archivo.resolve())

C:\Users\andry\AppData\Local\Programs\Microsoft VS Code\normativas_filtradas.xlsx
C:\Users\andry\AppData\Local\Programs\Microsoft VS Code\normativas_filtradas.csv